"project_id": "CROWDIN_PROJECT_ID"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

files:
  - source: /public/i18n/source.json
    translation: /%original_path%/%locale%.json
