project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."

preserve_hierarchy: true

files:
  - source: "public/i18n/source.json"
    translation: "public/i18n/%two_letters_code%.json"
